"""add agent registry models

Revision ID: 0002_agent_registry
Revises: 0001_initial_schema
Create Date: 2026-09-02 07:30:00.000000

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0002_agent_registry'
down_revision = '0001_initial_schema'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
        sa.Column('id', sa.String(length=64), nullable=False),
        sa.Column('name', sa.String(length=255), nullable=False),
        sa.Column('slug', sa.String(length=100), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('slug')
    )
    op.create_table('departments',
        sa.Column('id', sa.String(length=64), nullable=False),
        sa.Column('org_id', sa.String(length=64), nullable=False),
        sa.Column('name', sa.String(length=100), nullable=False),
        sa.Column('cost_center', sa.String(length=50), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=True),
        sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_departments_org_id', 'departments', ['org_id'], unique=False)
    op.create_table('users',
        sa.Column('id', sa.String(length=64), nullable=False),
        sa.Column('org_id', sa.String(length=64), nullable=False),
        sa.Column('email', sa.String(length=255), nullable=False),
        sa.Column('name', sa.String(length=255), nullable=False),
        sa.Column('role', sa.String(length=50), nullable=False),
        sa.Column('password_hash', sa.String(length=255), nullable=False),
        sa.Column('is_active', sa.Boolean(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=True),
        sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('email')
    )
    op.create_index('idx_users_org_id', 'users', ['org_id'], unique=False)
    op.create_table('agents',
        sa.Column('id', sa.String(length=64), nullable=False),
        sa.Column('org_id', sa.String(length=64), nullable=False),
        sa.Column('dept_id', sa.String(length=64), nullable=True),
        sa.Column('name', sa.String(length=255), nullable=False),
        sa.Column('slug', sa.String(length=255), nullable=False),
        sa.Column('description', sa.Text(), nullable=False),
        sa.Column('ai_type', sa.String(length=50), nullable=False),
        sa.Column('function', sa.String(length=100), nullable=True),
        sa.Column('owner', sa.String(length=255), nullable=False),
        sa.Column('owner_contact', sa.String(length=255), nullable=True),
        sa.Column('lifecycle_stage', sa.String(length=50), nullable=False),
        sa.Column('version', sa.String(length=50), nullable=True),
        sa.Column('time_in_stage_weeks', sa.Integer(), nullable=True),
        sa.Column('at_risk', sa.Boolean(), nullable=True),
        sa.Column('risk_note', sa.Text(), nullable=True),
        sa.Column('risk_level', sa.String(length=20), nullable=True),
        sa.Column('model_name', sa.String(length=100), nullable=True),
        sa.Column('model_provider', sa.String(length=100), nullable=True),
        sa.Column('runtime', sa.String(length=100), nullable=True),
        sa.Column('framework', sa.String(length=100), nullable=True),
        sa.Column('api_endpoint', sa.String(length=500), nullable=True),
        sa.Column('sla', sa.String(length=255), nullable=True),
        sa.Column('value_amount', sa.Integer(), nullable=True),
        sa.Column('value_type', sa.String(length=50), nullable=True),
        sa.Column('hours_saved_monthly', sa.Integer(), nullable=True),
        sa.Column('business_outcome', sa.Text(), nullable=True),
        sa.Column('tags', sa.JSON(), nullable=True),
        sa.Column('enterprise_systems', sa.JSON(), nullable=True),
        sa.Column('databases', sa.JSON(), nullable=True),
        sa.Column('knowledge_bases', sa.JSON(), nullable=True),
        sa.Column('mcp_servers', sa.JSON(), nullable=True),
        sa.Column('calls', sa.JSON(), nullable=True),
        sa.Column('consumers', sa.JSON(), nullable=True),
        sa.Column('inputs', sa.JSON(), nullable=True),
        sa.Column('outputs', sa.JSON(), nullable=True),
        sa.Column('source', sa.String(length=50), nullable=True),
        sa.Column('discovered_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('shadow_ai_risk', sa.String(length=20), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=True),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=True),
        sa.Column('deprecated_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('sunset_date', sa.Date(), nullable=True),
        sa.ForeignKeyConstraint(['dept_id'], ['departments.id'], ),
        sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('slug')
    )
    op.create_index('idx_agents_ai_type', 'agents', ['ai_type'], unique=False)
    op.create_index('idx_agents_dept_id', 'agents', ['dept_id'], unique=False)
    op.create_index('idx_agents_lifecycle_stage', 'agents', ['lifecycle_stage'], unique=False)
    op.create_index('idx_agents_model_name', 'agents', ['model_name'], unique=False)
    op.create_index('idx_agents_org_id', 'agents', ['org_id'], unique=False)
    op.create_table('agent_identities',
        sa.Column('agent_id', sa.String(length=64), nullable=False),
        sa.Column('service_account', sa.String(length=255), nullable=False),
        sa.Column('entra_agent_id', sa.String(length=255), nullable=True),
        sa.Column('api_key_hash', sa.String(length=255), nullable=True),
        sa.Column('permissions', sa.JSON(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=True),
        sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
        sa.PrimaryKeyConstraint('agent_id'),
        sa.UniqueConstraint('service_account')
    )
    op.create_table('audit_log',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('org_id', sa.String(length=64), nullable=False),
        sa.Column('actor', sa.String(length=255), nullable=False),
        sa.Column('action', sa.String(length=50), nullable=False),
        sa.Column('entity_type', sa.String(length=50), nullable=False),
        sa.Column('entity_id', sa.String(length=64), nullable=True),
        sa.Column('changes', sa.JSON(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=True),
        sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_audit_log_entity', 'audit_log', ['entity_type', 'entity_id'], unique=False)
    op.create_index('idx_audit_log_org_id', 'audit_log', ['org_id'], unique=False)
    op.create_table('cost_anomalies',
        sa.Column('id', sa.String(length=64), nullable=False),
        sa.Column('agent_id', sa.String(length=64), nullable=False),
        sa.Column('anomaly_type', sa.String(length=50), nullable=False),
        sa.Column('severity', sa.String(length=20), nullable=False),
        sa.Column('detected_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=True),
        sa.Column('details', sa.JSON(), nullable=True),
        sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('resolved_by', sa.String(length=255), nullable=True),
        sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_cost_anomalies_agent_id', 'cost_anomalies', ['agent_id'], unique=False)
    op.create_table('discoveries',
        sa.Column('id', sa.String(length=64), nullable=False),
        sa.Column('org_id', sa.String(length=64), nullable=False),
        sa.Column('suspected_name', sa.String(length=255), nullable=False),
        sa.Column('suspected_dept', sa.String(length=100), nullable=True),
        sa.Column('suspected_type', sa.String(length=50), nullable=True),
        sa.Column('source', sa.String(length=100), nullable=False),
        sa.Column('confidence', sa.Integer(), nullable=False),
        sa.Column('signal', sa.Text(), nullable=True),
        sa.Column('status', sa.String(length=50), nullable=True),
        sa.Column('shadow_ai_risk', sa.String(length=20), nullable=True),
        sa.Column('registered_agent_id', sa.String(length=64), nullable=True),
        sa.Column('first_seen', sa.Date(), nullable=False),
        sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=True),
        sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
        sa.ForeignKeyConstraint(['registered_agent_id'], ['agents.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_discoveries_org_id', 'discoveries', ['org_id'], unique=False)
    op.create_index('idx_discoveries_status', 'discoveries', ['status'], unique=False)
    op.create_table('governance_exceptions',
        sa.Column('id', sa.String(length=64), nullable=False),
        sa.Column('agent_id', sa.String(length=64), nullable=False),
        sa.Column('gate', sa.String(length=50), nullable=False),
        sa.Column('reason', sa.Text(), nullable=False),
        sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('approved_by', sa.String(length=255), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=True),
        sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_governance_exceptions_agent_id', 'governance_exceptions', ['agent_id'], unique=False)
    op.create_index('idx_governance_exceptions_expires_at', 'governance_exceptions', ['expires_at'], unique=False)
    op.create_table('governance_reviews',
        sa.Column('id', sa.String(length=64), nullable=False),
        sa.Column('agent_id', sa.String(length=64), nullable=False),
        sa.Column('gate', sa.String(length=50), nullable=False),
        sa.Column('status', sa.String(length=50), nullable=False),
        sa.Column('reviewer', sa.String(length=255), nullable=True),
        sa.Column('notes', sa.Text(), nullable=True),
        sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=True),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=True),
        sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_governance_reviews_agent_id', 'governance_reviews', ['agent_id'], unique=False)
    op.create_index('idx_governance_reviews_gate', 'governance_reviews', ['gate'], unique=False)
    op.create_index('idx_governance_reviews_status', 'governance_reviews', ['status'], unique=False)
    op.create_table('model_token_prices',
        sa.Column('id', sa.String(length=64), nullable=False),
        sa.Column('model_name', sa.String(length=100), nullable=False),
        sa.Column('provider', sa.String(length=50), nullable=False),
        sa.Column('input_price_per_1m', sa.Float(), nullable=False),
        sa.Column('output_price_per_1m', sa.Float(), nullable=False),
        sa.Column('cache_read_price_per_1m', sa.Float(), nullable=True),
        sa.Column('tier', sa.String(length=20), nullable=False),
        sa.Column('effective_from', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=True),
        sa.Column('effective_to', sa.DateTime(timezone=True), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_model_token_prices_model_name', 'model_token_prices', ['model_name'], unique=False)
    op.create_table('waste_findings',
        sa.Column('id', sa.String(length=64), nullable=False),
        sa.Column('agent_id', sa.String(length=64), nullable=False),
        sa.Column('waste_type', sa.String(length=50), nullable=False),
        sa.Column('severity', sa.String(length=20), nullable=False),
        sa.Column('monthly_waste_cents', sa.Integer(), nullable=True),
        sa.Column('recommendation', sa.Text(), nullable=True),
        sa.Column('status', sa.String(length=50), nullable=True),
        sa.Column('detected_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=True),
        sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_waste_findings_agent_id', 'waste_findings', ['agent_id'], unique=False)
    op.create_index('idx_waste_findings_status', 'waste_findings', ['status'], unique=False)
    op.create_table('agent_token_usage',
        sa.Column('agent_id', sa.String(length=64), nullable=False),
        sa.Column('bucket', sa.DateTime(timezone=True), nullable=False),
        sa.Column('model_name', sa.String(length=100), nullable=False),
        sa.Column('invocation_count', sa.Integer(), nullable=True),
        sa.Column('input_tokens', sa.Integer(), nullable=True),
        sa.Column('output_tokens', sa.Integer(), nullable=True),
        sa.Column('cached_tokens', sa.Integer(), nullable=True),
        sa.Column('cost_cents', sa.Integer(), nullable=True),
        sa.Column('latency_avg_ms', sa.Integer(), nullable=True),
        sa.Column('error_count', sa.Integer(), nullable=True),
        sa.Column('iterations_max', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
        sa.PrimaryKeyConstraint('agent_id', 'bucket', 'model_name')
    )
    op.create_index('idx_agent_token_usage_agent_id', 'agent_token_usage', ['agent_id'], unique=False)
    op.create_index('idx_agent_token_usage_bucket', 'agent_token_usage', ['bucket'], unique=False)
    op.create_table('agent_budgets',
        sa.Column('agent_id', sa.String(length=64), nullable=False),
        sa.Column('monthly_budget_cents', sa.Integer(), nullable=True),
        sa.Column('alert_threshold_pct', sa.Integer(), nullable=True),
        sa.Column('hard_stop_pct', sa.Integer(), nullable=True),
        sa.Column('current_month_spend_cents', sa.Integer(), nullable=True),
        sa.Column('budget_reset_day', sa.Integer(), nullable=True),
        sa.Column('max_tokens_per_invocation', sa.Integer(), nullable=True),
        sa.Column('max_iterations', sa.Integer(), nullable=True),
        sa.Column('auto_pause_on_breach', sa.Boolean(), nullable=True),
        sa.Column('last_alert_sent', sa.DateTime(timezone=True), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=True),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=True),
        sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
        sa.PrimaryKeyConstraint('agent_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('agent_budgets')
    op.drop_index('idx_agent_token_usage_bucket', table_name='agent_token_usage')
    op.drop_index('idx_agent_token_usage_agent_id', table_name='agent_token_usage')
    op.drop_table('agent_token_usage')
    op.drop_index('idx_waste_findings_status', table_name='waste_findings')
    op.drop_index('idx_waste_findings_agent_id', table_name='waste_findings')
    op.drop_table('waste_findings')
    op.drop_index('idx_model_token_prices_model_name', table_name='model_token_prices')
    op.drop_table('model_token_prices')
    op.drop_index('idx_governance_reviews_status', table_name='governance_reviews')
    op.drop_index('idx_governance_reviews_gate', table_name='governance_reviews')
    op.drop_index('idx_governance_reviews_agent_id', table_name='governance_reviews')
    op.drop_table('governance_reviews')
    op.drop_index('idx_governance_exceptions_expires_at', table_name='governance_exceptions')
    op.drop_index('idx_governance_exceptions_agent_id', table_name='governance_exceptions')
    op.drop_table('governance_exceptions')
    op.drop_index('idx_discoveries_status', table_name='discoveries')
    op.drop_index('idx_discoveries_org_id', table_name='discoveries')
    op.drop_table('discoveries')
    op.drop_table('cost_anomalies')
    op.drop_index('idx_audit_log_org_id', table_name='audit_log')
    op.drop_index('idx_audit_log_entity', table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_table('agent_identities')
    op.drop_index('idx_agents_org_id', table_name='agents')
    op.drop_index('idx_agents_model_name', table_name='agents')
    op.drop_index('idx_agents_lifecycle_stage', table_name='agents')
    op.drop_index('idx_agents_ai_type', table_name='agents')
    op.drop_index('idx_agents_dept_id', table_name='agents')
    op.drop_table('agents')
    op.drop_table('users')
    op.drop_index('idx_departments_org_id', table_name='departments')
    op.drop_table('departments')
    op.drop_table('organizations')
    # ### end Alembic commands ###
